[webservers]
vm1 ansible_host=3.17.182.240 server_number=1
vm2 ansible_host=3.144.209.160 server_number=2

[webservers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/jsu-ansible-key-mac.pem
ansible_python_interpreter=/usr/bin/python3
